"""criação da tabela Tokens, e vinculação com a tabela Cliente

Revision ID: 291f4c618380
Revises: cd2c0423c939
Create Date: 2025-11-12 15:40:56.476388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291f4c618380'
down_revision = 'cd2c0423c939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    # ### end Alembic commands ###
